export const NAMES = [
    `Akar`,
    `Avax`,
    `Axtin`,
    `Bennett`,
    `Buck`,
    `Codex`,
    `Coro`,
    `Crowbar`,
    `Cynder`,
    `Deavar`,
    `Durrek`,
    `Ender`,
    `Eclipse`,
    `Fang`,
    `Fiver`,
    `Flik`,
    `Gavr`,
    `Gideon`,
    `Gridor`,
    `Hazel`,
    `Hunter`,
    `Jinx`,
    `Kerrud`,
    `Knuckles`,
    `Kruel`,
    `Mara`,
    `Lunar`,
    `Mani`,
    `Nalex`,
    `Perra`,
    `Padar`,
    `Ratchet`,
    `Ripper`,
    `Syrus`,
    `Saria`,
    `Savaj`,
    `Selor`,
    `Syntax`,
    `Tiabak`,
    `Thoria`,
    `Thrasher`,
    `Torch`,
    `Valria`,
    `Valbak`,
    `Wort`,
    `Xian`,
    `Zandar`,
    `Zero`,
];

export const PERSONALITY = [
    `Hotheaded`,
    `Dull-witted`,
    `Brutal`,
    `Apathetic`,
    `Merciless`,
    `Apprehensive`,
    `Careless`,
    `Distracted`,
    `Intense`,
    `Narcissistic`,
    `Tricky`,
    `Vicious`,
    `Extravagant`,
    `Reckless`,
    `Irritable`,
    `Jittery`,
    `Lethargic`,
    `Rebellious`,
    `Resentful`,
    `Pompous`,
];

export const FLESH_SCARS = [
    `Burnt flesh`,
    `a Runny nose of neon-green mucus`,
    `One hand frostbitten and black`,
    `a Lost jaw, blown off by a thermal detonator`,
    `Missing middle fingers, flipped off the wrong person`,
    `Crazed bug eyes; you always look intense`,
    `No eyebrows; you pick at them constantly and then eat them`,
    `a Swollen, distended belly; the rest of you is lanky`,
    `a mouth completely devoid of teeth; rotted by StarDust`,
    `a case of Pus face, covered in acne`,
    `an Arthritic hip; you walk with a pronounced limp`,
    `Brother weak eyes; without glasses, you are useless`,
    `a Sloshy brain; so much damage you seem half-drunk all the time`,
    `a Seeping wound; constant, slow stream of pus leaks from your belly`,
    `thick Curling toenails that curve under your toes; you walk on your heels `,
    `perpetual Grave mouth; a vile stench comes from your facehole whenever you open it`,
    `Nervous; you’ve gnawed your nails almost completely off`,
    `Back blisters; carrying anything on your back causes horrible pain`,
    `a Missing ear, lost in a bet`,
    `No nose, ripped off your face by the teeth of a beast`,
];

export const BOT_SCARS = [
    `a Seeping wound; constant, slow stream of oil leaks from your belly`,
    `a Scorched shell`,
    `Sparks sputtering out of orifices `,
    `One hand rusted and squeaky`,
    `a Lost jaw, blown off by a thermal detonator`,
    `Missing middle fingers, flipped off the wrong person`,
    `Crazed bug eyes; you always look intense`,
    `No faceplate; open wiring looks like musculature`,
    `a body built of mismatched parts`,
    `a faceplace stained by StarDust`,
    `a bad case of Pulse face; electrical shorts that pop each time you are hit in the face`,
    `a Rusted hip; you walk with a pronounced limp`,
    `Brother weak eyes; without enhanced goggles, you are useless`,
    `Crossed wiring; so much damage you seem half-drunk all the time`,
    `Fused feet; you walk on your heels`,
    `perpetual Grave mouth; a vile stench comes from your facehole whenever you open it`,
    `Nervous; you've gnawed your paint almost completely off`,
    `Bad hydraulics; carrying anything on your back causes horrible pain`,
    `a Missing ear, lost in a bet`,
    `a Large dent in the middle of your faceplate, probably delivered by an angry programmer`,
];

export const IDIOSYNCRASIES = [
    `kleptomania, always with the shinies`,
    `a know-it-all attitude and an itching desire to let everyone know how much you know`,
    `a misplaced sense of confidence; you never back down`,
    `the disgusting title of "Snot Rocketeer", constantly blocking one nostril and blowing snot out of the other`,
    `alchoholism. If there’s alcohol, you will drink it past the point of excess`,
    `a belief that all insects to be würms and will smush any you see`,
    `toilet humor; farts amuse you to no end. If one is let loose, you will laugh even when trying to hide`,
    `a focus on the mundane, never remembering the important details`,
    `an analogy for every situation. You share it with any who will listen`,
    `an incessant itch inside your skull that you believe is a würm you call Fred. You talk to Fred`,
    `an insistence on always being in charge; you don’t take orders well from others`,
    `skitishness; unable to look anyone in the eye`,
    `fidgety fingers. Must always have something keeping your hands busy`,
    `a penchant to exaggerate everything you say in one way or another. You're full of shit`,
    `a crippling addition to StarDust. If there’s dust around, it’s going into your oxygen tank`,
    `paranoia. Always looking over your shoulder, thinking someone is after you`,
    `germaphobia. Everything must be clean and sterile `,
    `stress eating. When things get really stressful, you will eat anything just to consume`,
    `trichotillomania. Whenever you rest, you pull hairs out of your head`,
    `a sense of malase. You refuse to bathe or clean yourself in any way`,
];

export const BOT_IDIOSYNCRASIES = [
    `kleptomania, always with the shinies`,
    `a know-it-all attitude and an itching desire to let everyone know how much you know`,
    `a misplaced sense of confidence; you never back down`,
    `the disgusting title of "Snot Rocketeer", constantly blocking one nostril and blowing sparks out of the other`,
    `alchoholism. If there’s alcohol, you will drink it past the point of excess`,
    `a belief that all insects to be würms and will smush any you see`,
    `toilet humor; farts amuse you to no end. If one is let loose, you will laugh even when trying to hide`,
    `a focus on the mundane, never remembering the important details`,
    `an analogy for every situation. You share it with any who will listen`,
    `an incessant itch inside your skull that you believe is a würm you call Fred. You talk to Fred`,
    `an insistence on always being in charge; you don’t take orders well from others`,
    `skitishness; unable to look anyone in the eye`,
    `fidgety fingers. Must always have something keeping your hands busy`,
    `a penchant to exaggerate everything you say in one way or another. You're full of shit`,
    `a crippling addition to StarDust. If there’s dust around, it’s going into your oxygen tank`,
    `paranoia. Always looking over your shoulder, thinking someone is after you`,
    `germaphobia. Everything must be clean and sterile`,
    `stress eating. When things get really stressful, you will eat anything just to consume`,
    `trichotillomania. Whenever you rest, you pull wires out of your head`,
    `a sense of malase. You refuse to bathe or clean yourself in any way`,
];